info:
    serviceLinks:
        metrics: "{metricsHostname}/dashboard/db/openshift-project-spring-actuator-view?var-ds=openshift-{cluster}-ose&var-namespace={namespace}&var-app={name}"
        api-doc: "http://${ROUTE_NAME}/docs/index.html"
    podLinks:
        metrics: "{metricsHostname}/dashboard/db/openshift-project-spring-actuator-view-instance?var-ds=openshift-{cluster}-ose&var-namespace={namespace}&var-app={name}&var-instance={podName}"
    dependencies:
        skatteetaten: "skatteetaten"


aurora:
    #setting a db here will create a datasource from a database with that name.
    #in AOC config file
    db: REFERANSEAPP

spring:
    profiles:
        active: local

management:
    port: ${MANAGEMENT_HTTP_PORT}

logging:
    level:
      ske.aurora: DEBUG
      org:
        springframework: WARN
        apache.catalina: WARN
        hibernate: WARN

---
spring:
  profiles: local
  datasource:
    # id: 3f9d8558-0fd2-488e-8f79-fbbdf62b04ff
    url: jdbc:oracle:thin:@uil0map-drivein-db02:1521/dbhotel
    username: EIRJUPISSHOZYQAEVQPGWHVLVRJPDI
    password: vMJGXIptKxIbZZguunXBMoQvcZzYIG


management:
    port: 8081

logging:
    pattern:
      console: "%d [%-9.9thread] %-5level %logger %X - %msg %n%rEx{full}"
