info:
    application:
        name: "Aurora Spring Boot Server Referanseapplikasjon"
    links:
        metrics: "{metricsHostname}/dashboard/db/openshift-project-spring-actuator-view?var-ds=openshift-{cluster}-ose&var-namespace={namespace}&var-app={name}"
        logs: "{logsHostname}/en-US/app/search/search?q=search environment%3D{namespace} application%3D{name} sourcetype%3Dlog4j&display.page.search.mode=smart&dispatch.sample_ratio=1&earliest=-10m&latest"
        api-doc: "${ROUTE_NAME}/docs/index.html"
    dependencies:
        skatteetaten: "http://www.skatteetaten.no"

spring:
    profiles:
        active: local
    jackson:
        date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

management:
    health.status.order: DOWN, OUT_OF_SERVICE, UNKNOWN, COMMENT, UP
    port: ${MANAGEMENT_HTTP_PORT}

flyway:
  out-of-order: true


endpoints:
    health:
        mapping:
            COMMENT: OK
    metrics:
        enabled: false
    logfile:
        enabled: false
    autoconfig:
        enabled: false
    heapdump:
        enabled: false
    configprops:
        enabled: false
    mappings:
        enabled: false
    beans:
        enabled: false
    dump:
        enabled: false
    jolokia:
        enabled: false

aurora:
    metrics:
        prometheus:
            endpoint: /prometheus
            statusCodeMetric:
                mappings: /api/*

logging:
    level:
      ske.aurora: DEBUG
      org:
        springframework: WARN
        apache.catalina: WARN
        hibernate: WARN

---
spring:
  profiles: local
  datasource:
    # id: 3f9d8558-0fd2-488e-8f79-fbbdf62b04ff
    url: jdbc:oracle:thin:@uil0map-drivein-db02:1521/dbhotel
    username: EIRJUPISSHOZYQAEVQPGWHVLVRJPDI
    password: vMJGXIptKxIbZZguunXBMoQvcZzYIG

logging:
    pattern:
      console: "%d [%-9.9thread] %-5level %logger %X - %msg %n%rEx{full}"
