info:
    application:
        name: "Aurora Spring Boot Server Referanseapplikasjon"

spring:
    profiles:
        active: local
    jackson:
        date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

endpoints:
    metrics:
        enabled: false
    logfile:
        enabled: false
    autoconfig:
        enabled: false
    heapdump:
        enabled: false
    configprops:
        enabled: false
    mappings:
        enabled: false
    beans:
        enabled: false
    dump:
        enabled: false
    jolokia:
        enabled: false

management:
    port: 8081

aurora:
    metrics:
        prometheus:
            endpoint: /prometheus
            statusCodeMetric:
                mappings: /api/*

logging:
    file: logs/application.log
    pattern:
      console: "%d [%-9.9thread] %-5level %logger{36} %X - %msg %n%rEx{full}"
      file: "%d [%-9.9thread] %-5level %logger{36} %X - %msg %n%rEx{full}"

    level:
      ske.aurora: DEBUG
---
spring:
  profiles: local
  datasource:
    # id: 3f9d8558-0fd2-488e-8f79-fbbdf62b04ff
    url: jdbc:oracle:thin:@uil0map-drivein-db02:1521/dbhotel
    username: EIRJUPISSHOZYQAEVQPGWHVLVRJPDI
    password: vMJGXIptKxIbZZguunXBMoQvcZzYIG